[project]
name = "magic-pocket-cli"
version = "0.1.1"
description = "CLI and deploy tools for magic-pocket."
requires-python = ">=3.10"
dependencies = [
    "magic-pocket>=0.1.1",
    "click>=8.1.7",
    "jinja2>=3.1.3",
    "python-on-whales>=0.68.0",
    "deepdiff>=6.7.1",
    "pyyaml>=6.0.1",
    "requests>=2.31.0",
]

[project.scripts]
pocket = "pocket_cli.cli.main_cli:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["pocket_cli"]

[tool.uv.sources]
magic-pocket = { workspace = true }
